### ISSUE TITLE
mash command hang due to wrapping of memcpy

### ISSUE THREAD

**Issue by boegel** [marbl/Mash#103]
After building Mash 2.1 from source using GCC 7.3.0, I noticed that trivial commands like `mash --version` were hanging (no output even after waiting for minutes, but 100% CPU).

Through some debugging with GDB, I found out that the wrapping of `memcpy` (see https://github.com/marbl/Mash/blob/master/src/mash/memcpyLink.h) is the culprit:

```
(gdb) bt
#0  0x0000000000406050 in __wrap_memcpy ()
#1  0x00000000004060e1 in void std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_construct<char*>(char*, char*, std::forward_iterator_tag) [clone .isra.34] ()
#2  0x0000000000404f62 in __static_initialization_and_destruction_0(int, int) [clone .constprop.71] ()
#3  0x0000000000466eed in __libc_csu_init ()
#4  0x00007ffff6f5a3d5 in __libc_start_main () from /lib64/libc.so.6
#5  0x0000000000405f8f in _start ()
```

And indeed, disabling the wrapping of `memcpy` fixed the problem:

```diff
--- Mash-2.1.orig/Makefile.in	2018-10-07 23:43:17.000000000 +0200
+++ Mash-2.1/Makefile.in	2018-12-10 16:39:51.947255000 +0100
@@ -5,9 +5,9 @@

 ifeq ($(UNAME_S),Darwin)
 	CXXFLAGS += -mmacosx-version-min=10.7 -stdlib=libc++
-else
-	CXXFLAGS += -include src/mash/memcpyLink.h -Wl,--wrap=memcpy
-	CFLAGS += -include src/mash/memcpyLink.h
+#else
+#	CXXFLAGS += -include src/mash/memcpyLink.h -Wl,--wrap=memcpy
+#	CFLAGS += -include src/mash/memcpyLink.h
 endif

 SOURCES=\
```

Why is `memcpy` being wrapped to `memcpy@GLIBC_2.2.5`?

https://stackoverflow.com/questions/8823267/linking-against-older-symbol-version-in-a-so-file tell me it may be because of semantic changes to `memcpy`, and suggests that the proper fix is to actually use `memmove` rather than `memcpy`?

**Comment by ondovb** [comment]
The wrapper allows us to generate binaries that run on old Linux distros, similar to the situation described in that SO question. This really only matters if you are planning to distribute though, so this could be gotten around with some kind of flag to enable the wrapper. The actual problem with hanging might take some time to look into.
