### ISSUE TITLE
Problem with mash. can't read file

### ISSUE THREAD

**Issue by alanxelena** [marbl/Mash#173]
Hi!

  I am having some trouble while using mash through bbmap in Windows. I am trying to perform a sketch out of a couple of assembled reads. I am using the following command:
 
bash sketch.sh --in=*.fasta --size=10000 --out=mash_sketch

But I get the following:

Executing sketch.SketchMaker [in=*.fasta, size=10000, out=mash_sketch]

Exception in thread "main" java.lang.RuntimeException: Can't read file '*.fasta'
        at shared.Tools.testInputFiles(Tools.java:185)
        at sketch.SketchMaker.<init>(SketchMaker.java:272)
        at sketch.SketchMaker.main(SketchMaker.java:66)

I am currently in the directory I should be in (The one containing the fasta files). I have also tried using only one file as input (so as to avoid the *.fasta) and writing the file name between "" but I always get the same error message.

Any idea of what the problem might be? I would really appreciate any help.

Thank you!

**Comment by kalebabram** [comment]
If you use `mash paste` you can provide a text file with the file path of each individual sketch on a separate line. 

For example you could run:
mash paste my_concat_sketch -l /fp/to/list/of/sketch/fps
